### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by bastienk** [rethinkdb/logstash-input-rethinkdb#14]
Hello,

I am trying to use this plugin with my rethinkdb hosted on compose.io. However I noticed that ssl isn't supported, do you plan to do this in the future?

Thanks

**Comment by deontologician** [comment]
It's not planned at the moment. The source is pretty simple though, it just involves adding some connection options. Any interest in submitting a PR?

**Comment by bastienk** [comment]
Submitted!
https://github.com/rethinkdb/logstash-input-rethinkdb/pull/15
