### ISSUE TITLE
Unregistering table 

### ISSUE THREAD

**Issue by stevns** [rethinkdb/logstash-input-rethinkdb#6]
Executing the following conf file in logstach:

input {rethinkdb
   {host => "localhost"
    port => 28015
    auth_key => ""
    watch_dbs => ["customer"]
    watch_tables => ["customer.scv"]
    backfill => true
    }}
output {stdout {codec => json_lines}}

I receive the following error when executing:

Settings: Default filter workers: 2
Logstash startup completed
Eventmachine loop started
Creating db feed for customer
Watching table customer.scv []
Database `customer` does not exist.
Backtrace:
r.db("customer").table(
^^^^^^^^^^^^^^^^
  "scv"
).changes({"include_initial" =>
     true,
   "squash" =>
     true,
   "include_states" =>
     true}
) {:level=>:error}
Unregistering table customer.scv
Feed for db 'customer' registered

OS: CentOS 6.7
java version "1.8.0_66"
Logstash 2.1.1
RethinkDB 2.2.3-1
DB and table: customer.scv (840K docs)

**Comment by stevns** [comment]
pebkac

**Comment by deontologician** [comment]
Just wanted to mention I saw this! If you run into more issues, do feel free to open an issue. The plugin is pretty new so there are definitely potential bugs
